-- phpMyAdmin SQL Dump
-- version 5.0.1
-- https://www.phpmyadmin.net/
--
-- Servidor: 127.0.0.1
-- Tiempo de generación: 22-06-2021 a las 13:34:35
-- Versión del servidor: 10.4.11-MariaDB
-- Versión de PHP: 7.4.3

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de datos: `peliculas`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `peliculas`
--

CREATE TABLE `peliculas` (
  `id` int(20) NOT NULL,
  `titulo` varchar(180) NOT NULL,
  `fecha` varchar(100) NOT NULL,
  `imagen` varchar(200) NOT NULL,
  `calificacion` decimal(5,1) NOT NULL,
  `imdb` varchar(500) NOT NULL,
  `tmdb` varchar(500) NOT NULL,
  `info` varchar(2000) NOT NULL,
  `info2` varchar(2000) NOT NULL,
  `genre` varchar(100) NOT NULL,
  `video` varchar(1000) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Volcado de datos para la tabla `peliculas`
--

INSERT INTO `peliculas` (`id`, `titulo`, `fecha`, `imagen`, `calificacion`, `imdb`, `tmdb`, `info`, `info2`, `genre`, `video`) VALUES
(1, 'ALIEN', '1979', 'https://ep00.epimg.net/elpais/imagenes/2017/04/05/album/1491408345_526782_1491408652_album_normal.jpg', '3.8', 'https://www.imdb.com/title/tt0078748/?ref_=nv_sr_srsg_0', 'https://www.themoviedb.org/movie/348-alien', 'La nave comercial Nostromo es desviada para investigar una señal procedente de un planeta desconocido. Cuando algunos de sus miembros están en pleno reconocimiento, se dan cuenta de que no se trataba de una señal de ayuda sino de una advertencia. Pero ya es tarde, y no pueden evitar que un letal ser alienígena se introduzca en la nave, sembrando la muerte entre sus siete tripulantes.\r\n\r\n\r\n', 'Un hito de la ciencia-ficción que sigue las fórmulas de las películas de serie B de los años 50 (de hecho se inspira en el clásico “It, the Terror from Beyond Space”) y del thriller de suspense. Ridley Scott, su director, estaba tan obsesionado en crear esta sensación que incluso hizo que los actores no supieran qué les iba a suceder durante el rodaje de algunas escenas, con la intención de que este efecto fuese lo más real posible.\r\n', 'Ciencia Ficcion, Terror', 'LjLamj-b0I8'),
(2, 'INTERESTELLAR', '2014', 'https://i.ebayimg.com/00/s/MTYwMFgxMDY2/z/zu4AAOSw2spbJQ0J/$_57.JPG?set_id=8800005007', '4.2', 'https://www.imdb.com/title/tt0816692/?ref_=nv_sr_srsg_0', 'https://www.themoviedb.org/movie/157336-interstellar', 'La trama de Interstellar está ambientada en lo que, aparentemente, es un futuro cercano, en el que la Tierra se ve afectada por una serie de acontecimientos climáticos y biológicos catastróficos que hacen más difícil la vida de la humanidad y de los seres vivos. En este contexto, el piloto e ingeniero Joseph Cooper (Matthew McConaughey), es reclutado por el Dr. John Brandt (Michael Caine), director de la NASA, para dirigir una misión especial que podría representar la última esperanza de la humanidad para evitar la extinción. ', 'Así, se une a la Dra. Amelia Brandt (Anne Hathaway) -bióloga, hija del Dr. Brandt-, al Dr. Romilly (David Gyasi) -físico-, al Dr. Doyle (Wes Bentley) -geógrafo-, y a los robots asistentes TARS (Bill Irwin) y CASE (Josh Stewart), para pilotar el Endurance en un viaje a través de agujeros de gusano, planetas extrasolares y un agujero negro, con el objetivo de encontrar un nuevo hábitat para la vida en la Tierra. Todo ello mientras Cooper, preocupado por los efectos temporales del viaje interestelar, intenta mantener una relación con su querida hija, Murphy (Mackenzie Foy; Jessica Chastain; Ellen Burstyn).', 'Ciencia Ficcion', 'UoSSbmD9vqc'),
(3, 'DOCTOR WHO', '1963 - 2017', 'https://images-na.ssl-images-amazon.com/images/I/91-mgsziAEL.jpg', '2.8', 'https://www.imdb.com/title/tt0056751/?ref_=nv_sr_srsg_3', 'https://www.themoviedb.org/tv/121-doctor-who', 'El Doctor está de vuelta. Esta nueva producción retoma la historia que acabó con la serie \'Doctor Who\' original que llegó a su fin en el año 1989. Este famoso alienígena es un Señor del Tiempo, una raza casi extinta cuyos miembros tienen la habilidad de viajar en el tiempo y el espacio.\r\n\r\n', 'En esta ocasión, el encargado de dar vida al Doctor más famoso de la televisión británica es Cristopher Eccleston (\'Héroes\', \'The League of Gentlemen\'). Junto a su compañera Rose Tyler (Billie Piper, \'Servicio completo\', \'Evita\') y por medio de la máquina del tiempo TARDIS -Time and Relative Dimension in Space- el protagonista viaja en el tiempo y el espacio para vivir las aventuras más increíbles en épocas y dimensiones extraordinarias.', 'Ciencia Ficcion', 'nNf_9igdsDw'),
(4, 'MISION IMPOSIBLE FALLOUT', '2018', 'https://www.aceprensa.com/wp-content/uploads/elementor/thumbs/353081-0-od64eshq8bnwmec546t16jwr4lllfhklgmn1h8o934.jpg', '3.0', 'https://www.imdb.com/title/tt4912910/?ref_=nv_sr_srsg_0', 'https://www.themoviedb.org/movie/353081-mission-impossible-fallout', 'Bajo la dirección de Christopher McQuarrie, vuelve a la carga Ethan hunt (Tom Cruise), agente de operaciones de campo para el IMF, una agencia de élite dedicada al espionaje que se encarga de llevar a cabo peligrosas y altamente sensibles misiones internacionales que han sido consideradas como \"imposibles\".\r\n\r\n\r\n\r\n', 'En esta entrega descubrimos más a fondo la personalidad de Ethan Hunt que llega acompañado de Henry Cavill, Vanessa Kirby, entre otros y también volvemos a ver a la espía del MI6 Ilsa Faust (Rebecca Ferguson) y conocemos a la nueva directora de la CIA (Angela Bassett). Además, vuelven otros personajes conocidos de la saga como Luther Stickell (Ving Rhames), Benji Dunn (Simon Pegg) y Alan Hunley (Alec Baldwin).\r\n\r\nUna carrera contrarreloj después de una misión fallida.', 'Accion', 'Wev1ym1Nc8o'),
(5, 'CORALINE', '2009', 'https://historiasdeterror10.com/wp-content/uploads/2019/09/Los_mundos_de_Coraline-693377106-large.jpg', '4.5', 'https://www.imdb.com/title/tt0327597/?ref_=nv_sr_srsg_0', 'https://www.themoviedb.org/movie/14836-coraline', 'Basada en Coraline, la exitosa novela del escritor británico Neil Gaiman, Los mundos de Coraline gira en torno a una niña llamada Coraline Jones (a la que dobla Dakota Fanning) que, con tan solo 11 años de edad, sueña con vivir miles de experiencias.\r\n\r\nLa pequeña acaba de mudarse junto a sus padres a Oregón. Según pasan los días, no puede evitar echar en falta a todos los amigos que ha dejado en Michigan. Además, desde que llegaron al nuevo vecindario, Caroline siente que su familia está cada vez más ocupada y le prestan menos atención. Tan solo Wybie Lovat, su joven vecino, parece mostrarse interesado en ella.\r\n\r\n', 'Coraline acaba descubriendo en su casa una puerta secreta que, al ser cruzada, transporta a las personas a un mundo paralelo semejante a sus vidas pero mucho más divertido. Allí la gente es más simpática y más cariñosa y la niña se siente muy a gusto. Sin embargo, cuando descubre que la nueva versión de su madre planea quedarse con ella para siempre, Coraline no tendrá más remedio que trazar un plan para salvarse y volver con los suyos.', 'Infantil, Suspense', 'rvPYIBM3RN4'),
(6, '1917', '2019', 'https://theend.biblioteca.ulpgc.es/wp-content/uploads/2020/10/1917.jpg', '5.0', 'https://www.imdb.com/title/tt8579674/?ref_=nv_sr_srsg_0', 'https://www.themoviedb.org/movie/530915-1917', 'Primera Guerra Mundial, conocida en su momento como la Gran Guerra. En el frente occidental, el general británico Erinmore (Colin Firth) encomienda a los cabos Schofield (George MacKay) y Blake (Dean-Charles Chapman), dos jóvenes soldados británicos, una misión estrictamente imposible. Deberán entregar un mensaje urgente y decisivo al coronel MacKenzie (Benedict Cumberbatch). Para realizar esta misión deberán abandonar la trinchera a plena luz del día y avanzar por el campo francés ocupado por los alemanes. ', 'Sin respiro, en una carrera a contrarreloj, los dos soldados atravesarán angostas trincheras, alambradas y campo a través en un entorno de muerte y destrucción, rodeado de cadáveres de hombres y animales. Solo disponen de unas pocas horas para cumplir su cometido y evitar a toda costa un violento ataque. Si no llegan a tiempo, 1.600 soldados perderán la vida, entre ellos el hermano de uno de los dos jóvenes soldados.', 'Accion, Belico ', 'SBc69RKIqwg'),
(7, 'EXPEDIENTE WARREN', '2013', 'https://playmax.xyz/img/c/400/9/1441459554/4448.jpg', '3.3', 'https://www.imdb.com/title/tt1457767/?ref_=nv_sr_srsg_3', 'https://www.themoviedb.org/movie/138843-the-conjuring', '\'The Conjuring\' cuenta la terrorífica historia de la familia Perron; una familia que, en la década de los 70, afirmó haber contactado con espíritus malvados en su domicilio del estado de Rhode Island. Sus presuntos encuentros sobrenaturales fueron estudiados e investigados por Ed y Lorraine Warren (Interpretados en la película por Patrick Wilson y Vera Farmiga). ', 'Lorraine es medium y Ed es un reputado investigador. Ambos se dedican al estudio de casos espirituales y paranormales. Lorraine no tarda en descubrir que las apariciones están relacionadas con el espíritu de un niño y una misteriosa caja de música que lleva en la casa varias décadas.', 'Terror', '1kOlrEwTfco'),
(8, 'SAW 1', '2005', 'https://es.web.img3.acsta.net/medias/nmedia/18/89/75/36/20065254.jpg', '4.0', 'https://www.imdb.com/title/tt0387564/?ref_=nv_sr_srsg_0', 'https://www.themoviedb.org/movie/176-saw', 'Desde el primer fotograma de \"Saw\", el espectador se enfrenta a lo desconocido: dos hombres se despiertan encadenados a la pared de un lavabo subterráneo. Lo único que saben es que uno de ellos debe matar al otro antes de ocho horas o ambos morirán. Esta película, de trama intrincada y final sorprendente, constituye una intensa y compleja incursión en el suspense, con un tratamiento visceral y asombrosamente humano del terror que ha hecho estremecer al público en todos los lugares en los que se ha estrenado. En \"Saw\", todas las víctimas deben afrontar una elección horrible de la que depende su vida. ', 'Un hombre sólo puede librarse de morir enterrado en vida escapando a través de una red de alambre cortante, una mujer debe matar a otro hombre para poder liberarse de una carcasa metálica programada para arrancarle la mandíbula, etc. Estos juegos, orquestados por un asesino conocido únicamente como Jigsaw («rompecabezas»), elevan a \"Saw\" por encima de las andanzas de los asesinos en serie típicos de las películas y aportan una inesperada nota macabra a la persistente atmósfera de terror de este thriller.', 'Terror, Slasher', 'WrFTmZwe5wc'),
(9, 'LUCY', '2014', 'https://elmonstruodelplacard.files.wordpress.com/2014/11/lucy.jpg', '2.3', 'https://www.imdb.com/title/tt2872732/?ref_=nv_sr_srsg_9', 'https://www.themoviedb.org/movie/240832-lucy', 'Lucy (Scarlett Johanson, Don Jon) es una joven que ejerce de \"mula\", se dedica a ocultar droga en su cuerpo para narcotraficantes. Pero un día, inesperadamente, una de las bolsas de droga que transporta se rompe y su sistema absorbe dichos estupefacientes. ', 'Lo sorprendente es que, en lugar de ir directa al hospital, las drogas le otorgan una serie de poderes sobrehumanos tales como telequinesis, la cancelación de dolor, la habilidad de absorber el conocimiento de forma instantánea y una velocidad espectacular; poderes que, inevitablemente, cambiarán su vida para siempre, convirtiendo a Lucy en una máquina de matar.\r\n\r\n\r\nEl film de acción escrito y dirigido por Luc Besson, creador de El quinto elemento y recientemente Malavita, cuenta también entre su reparto con los actores Morgan Freeman (Plan en Las Vegas) y Mink-sik Choi (Old Boy).', 'Suspense', 'YibFcTkJu3U'),
(10, 'ORIGEN', '2010', 'https://es.web.img3.acsta.net/medias/nmedia/18/72/41/74/20198901.jpg', '4.9', 'https://www.imdb.com/title/tt1375666/?ref_=nv_sr_srsg_0', 'https://www.themoviedb.org/movie/27205-inception', 'Dom Cobb (Leonardo DiCaprio) es el mejor extractor. Su oficio consiste en introducirse en los sueños de sus víctimas y extraerle secretos del mundo de los negocios para luego venderlos con grandes dividendos. Debido a sus arriesgados métodos, grandes consorcios lo tienen en la mirilla, y ningún escondite le ofrece seguridad. No puede regresar a los Estados Unidos donde sus hijos le esperan. El empresario Saito (Ken Watanabe) le recluta para su última misión, que de triunfar le podría permitir su ansiado regreso a casa. Se trata de una misión muy difícil. ', 'Cobb y su equipo estrella, no robarán un secreto, sino que deben implantar una idea en el subconsciente del heredero de una multinacional (Cillian Murphy), quien se ha convertido en un peligro para Saito. Cobb y su equipo se preparan meticulosamente para la misión, pero no presienten un riesgo incalculable: el espectro de Mal (Marion Cotillard), la difunta esposa de Cobbs quien aun ronda sus pensamientos...', 'Accion, Suspense', 'RV9L7ui9Cn8'),
(11, 'KILL BILL VOL.1', '2003', 'http://elcatalogo.files.wordpress.com/2009/05/kill-bill-2003.jpg', '4.1', 'https://www.imdb.com/title/tt0266697/?ref_=nv_sr_srsg_0', 'https://www.themoviedb.org/movie/24-kill-bill-vol-1', 'La sinopsis es bien sencilla. Una mujer (Uma Thurman) despierta del coma cuatro años después de haber recibido una bala en la cabeza durante el ensayo de su boda. Todos los asistentes murieron acribillados, incluido el que iba a ser su marido. La matanza fue perpetrada por el Escuadrón Asesino Víbora Letal, unos asesinos profesionales liderados por Bill (David Carradine). La mujer, conocida como La Novia, pone en marcha su venganza contra Bill y todos sus secuaces.\r\n\r\n', 'El Escuadrón Asesino Víbora Letal está formado por cinco miembros. La lista de La Novia la componen O-Ren Ishii (Lucy Liu), Vernita Green (Vivica A. Fox), Budd (Michael Madsen), Elle Driver (Daryl Hannah) y Bill. En la primera parte La Novia tiene en su lista a O-Ren Ishii y a Vernita Green.', 'Accion', '7kSuas6mRpk'),
(12, 'TENET', '2020', 'https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/poster-tenet-1593638789.jpeg?crop=1xw:1xh;center,top&resize=480:*', '4.5', 'https://www.imdb.com/title/tt6723592/?ref_=nv_sr_srsg_0', 'https://www.themoviedb.org/movie/577922-tenet', 'En el mundo del espionaje internacional, un hombre (John David Washington) prefiere morir antes que entregar a sus compañeros. Tras conseguir superar esta difícil prueba, este hombre tendrá una importante misión: evitar una nueva amenaza mucho más peligrosa que la tercera guerra mundial. La clave será una sola palabra: TENET. ', 'Será entonces cuando tenga que hacer frente a un terrible villano (al que da vida Kenneth Branagh), un tipo que parece que puede viajar en el tiempo y mandar información al futuro. Ayudado por la mujer de éste (interpretada por Elizabeth Debicki), el protagonista trama un plan para salvar la vida en la Tierra tal y como la conocemos.', 'Accion, Suspense', 'QxhDXmb2O3k'),
(17, 'The Dark Knight', '2008', 'https://images-na.ssl-images-amazon.com/images/I/91KkWf50SoL._SL1500_.jpg', '4.5', 'https://www.imdb.com/title/tt0468569/?pf_rd_m=A2FGELUUNOQJNL&pf_rd_p=e31d89dd-322d-4646-8962-327b42fe94b1&pf_rd_r=1NP02MJJECHGVVD2GCAM&pf_rd_s=center-1&pf_rd_t=15506&pf_rd_i=top&ref_=chttp_tt_4', 'https://www.themoviedb.org/movie/155-the-dark-knight?language=es-ES', 'Batman/Bruce Wayne regresa para continuar su guerra contra el crimen. Con la ayuda del teniente Jim Gordon y del Fiscal del Distrito Harvey Dent, Batman se propone destruir el crimen organizado en la ciudad de Gotham.', 'El triunvirato demuestra su eficacia, pero, de repente, aparece Joker, un nuevo criminal que desencadena el caos y tiene aterrados a los ciudadanos.', 'Accion, Drama', 'EXeTwQWrcwY'),
(18, 'Un Lugar Tranquilo 2', '2021', 'https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/lugar-tranquilo-2-poster-nuevo-1582539316.jpg?resize=480:*', '4.5', 'https://www.imdb.com/title/tt8332922/?ref_=nv_sr_srsg_0', 'https://www.themoviedb.org/movie/520763-a-quiet-place-2?language=es-ES', 'Tras los fatales acontecimientos sucedidos en la primera parte, la familia Abbot (Emily Blunt, Millicent Simmonds y Noah Jupe) debe enfrentarse a los peligros del mundo exterior mientras luchan en silencio por sobrevivir. ', 'Forzados a aventurarse en lo desconocido, pronto se dan cuenta de que las criaturas que cazan orientadas por el sonido no son la única amenaza que acecha más allá del camino de arena. Secuela de la exitosa producción \"Un lugar tranquilo\" (A Quiet Place, 2018).', 'Terror, Suspense ', 'hdNBjCwXIUs'),
(19, 'Niños Grandes', '2010', 'https://es.web.img3.acsta.net/medias/nmedia/18/95/85/19/20533585.jpg', '3.5', 'https://www.imdb.com/title/tt1375670/?ref_=nv_sr_srsg_0', 'https://www.themoviedb.org/movie/38365-grown-ups?language=es-ES', 'Después de treinta años, cinco amigos vuelven a verse para asistir al funeral de su entrenador de baloncesto de la infancia. Con sus esposas e hijos a cuestas, deciden pasar el fin de semana del 4 de julio en una casa cerca de un lago, en la que muchos años antes habían celebrado la conquista de un campeonato.', 'Curiosamente, esos días de convivencia les harán comprender que, a pesar de que ya son personas adultas, en realidad no han madurado.', 'Comedia', 'ATUCOOauAos'),
(22, 'La Princesa Mononoke', '1997', 'https://www.vertigofilms.es/wp-content/uploads/2019/08/immg.png', '5.0', 'https://www.imdb.com/title/tt0119698/?ref_=nv_sr_srsg_0', 'https://www.themoviedb.org/movie/128?language=es-ES', 'Tras sufrir el ataque de un monstruoso jabalí maldito, el joven Ashitaka emprende el camino en busca de la cura que detenga la infección. Mientras, los humanos están acabando con los bosques y los dioses convertidos en temibles bestias hacen todo lo posible por protegerlo encabezados por Mononoke, una princesa guerrera.', 'Ashikata deberá escoger bando y decidir si ayudar a los hombres o las deidades intentando detener la maldición de su herida que se extiende por su cuerpo sin cuartel', 'Animacion', '4OiMOHRDs14');

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `peliculas`
--
ALTER TABLE `peliculas`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT de las tablas volcadas
--

--
-- AUTO_INCREMENT de la tabla `peliculas`
--
ALTER TABLE `peliculas`
  MODIFY `id` int(20) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=26;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
